import type { Metadata } from 'next';
import { Inter, Hind_Siliguri, Tiro_Bangla, Baloo_Da_2 } from 'next/font/google'; 
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// ফন্ট ১: Hind Siliguri
const hindSiliguri = Hind_Siliguri({
  subsets: ['bengali'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-hind-siliguri', 
});

// ফন্ট ২: Tiro Bangla (Serif)
const tiroBangla = Tiro_Bangla({
  subsets: ['bengali'],
  weight: ['400'], // <-- পরিবর্তন: '700' এখান থেকে সরানো হয়েছে
  variable: '--font-tiro-bangla',
});

// ফন্ট ৩: Baloo Da 2 (Rounded)
const balooDa2 = Baloo_Da_2({
  subsets: ['bengali'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-baloo-da-2',
});

export const metadata: Metadata = {
  title: 'Dynamic Thumbnail Generator (TSX)',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${hindSiliguri.variable} ${tiroBangla.variable} ${balooDa2.variable}`}>
        {children}
      </body>
    </html>
  );
}